### ISSUE TITLE
Swapping keymaps

### ISSUE THREAD

**Issue by KenJean** [cabra-arretado/mini-vimrc-obsidian#16]
Just wondering if there was anyway to do a straight swap of keymaps - this because I use an alternate keyboard layout.

For example:
`map y h`
works just fine, but if I follow that with
`map h y`
then both maps fail to work. Obviously there is a circular remapping going on. 

I tried various combinations in conjuction with `unmap`, but none seem to work.

⇒ KJ

**Comment by cabra-arretado** [comment]
@KenJean I am gonna investigate. This might be a limitation of the CodeMirror API, but I am not sure.

**Comment by KenJean** [comment]
Ah, thanks for getting back to me. Don't go to too much trouble, I can live
with these few simple remappings - this is already a great convenience for
me.


⇒ KJ

**Comment by cabra-arretado** [comment]
@KenJean, thanks for bringing that to my attention. This is fixed in the new `v1.1.0`. Just released.
